# Use Ctrl + a as the prefix
# This feels much better than the Ctrl + b which is hard to reach
unbind C-b
set -g prefix C-a
bind a send-prefix

# Respond to mouse
set -g mouse on

# Set the pane indexing to start from 1 instead of 0
# Makes things easier to reach
set -g base-index 1

# Better pane splitting
# - v does vertical splitting
# - s does horizontal splitting
# In both these cases and the existing case when using `c` (to open a new pane),
# open it with the current path of the pane that we're already on. This is
# great because in a tmux window we usually move around dirs and then on a
# dir we want to do some function so we open off a pane, and that pane starts
# in the place where tmux originally started. Which is annoying.
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Vim everythannnggg!
setw -g mode-keys vi

# Use Enter to enter copy-mode
bind Enter copy-mode

# Match the copy mode semantics as closely to vim movements as possible
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel

# Always copy to the OS clipboard (YAY clipboard managers!)
set -g set-clipboard on

set -g history-limit 50000

# Quick clean status bar with highlight for which window I'm on
# And for a good right side datetime etc
set -g status-right " %H%M | %Y-%m-%d | %A "
set -g window-status-current-format "›#I:#W‹"
set -g window-status-format " #I:#W "

set -sg escape-time 0
set -g focus-events on

# Terminal/color support
set -g default-terminal "tmux-256color"

set -as terminal-features ",xterm-ghostty:RGB"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",tmux-256color:RGB"
set -as terminal-features ",screen-256color:RGB"
